title: Jekyll Commerce Starter
description: Reusable Jekyll ecommerce storefront
url: ""
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  products:
    output: true
    permalink: /products/:name/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor